### ISSUE TITLE
CLI on Homebrew?

### ISSUE THREAD

**Issue by louwers** [Outdooractive/mvt-tools#20]
Would be very convenient to have the CLI available on Homebrew.

**Comment by trasch** [comment]
Duplicate to #4 

So far I have been shying away from the effort, but I am going to tackle it in the next couple of days...

**Comment by louwers** [comment]
Sorry, missed that one.

**Comment by trasch** [comment]
> Sorry, missed that one.

No problem at all. You should now be able to install it with

```

```

**Comment by trasch** [comment]
@louwers Also, feedback is very welcome. Don't hesitate to open an issue if you need more functionality or have other questions...
